chunk: 16
n_previous: 4
n_view: 1

model:
  
  pretrained_checkpoint: PATH_TO_CHECKPOINT

  auto_padzero_input_block: False
  auto_padrand_input_block: False

  base_learning_rate: 5e-5
  scale_lr: False
  target: lvdm.models.ddpm3d.ACWMLatentDiffusion
  params:
    rescale_betas_zero_snr: True
    parameterization: "v"
    linear_start: 0.00085
    linear_end: 0.012
    num_timesteps_cond: 1
    log_every_t: 20
    timesteps: 1000
    first_stage_key: ["video", "traj"]
    cond_stage_key: delta_action
    cond_stage_trainable: False
    image_proj_model_trainable: True
    traj_prompt_proj_model_trainable: True
    conditioning_key: hybrid
    image_size: [10, 16]
    channels: 4
    scale_by_std: False
    scale_factor: 0.18215
    use_ema: False
    uncond_prob: 0.1
    uncond_type: 'zero_embed'
    rand_cond_frame: true
    use_dynamic_rescale: true
    base_scale: 0.7
    fps_condition_type: 'fps'
    perframe_ae: True
    ae_batch_size: 2
    chunk: ${chunk}
    n_view: ${n_view}

    ### raymap: 3 direction + 3 origin maps
    use_raymap_dir: True
    use_raymap_origin: True
    ### dropout mask: 1
    use_cat_mask: True

    sparse_memory: True
    ddim_num_chunk: 1
    views_name_wo_imgcat: ["left_hand", "right_hand"]

    unet_config:
      target: lvdm.modules.networks.openaimodel3dcausal.UNetModel
      params:
        ### img(4) + mask(1) + cond img(4) + traj(4) + ray(6)
        in_channels: 19
        out_channels: 4
        model_channels: 320
        attention_resolutions:
        - 4
        - 2
        - 1
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 4
        - 4
        dropout: 0.1
        num_head_channels: 64
        transformer_depth: 1
        context_dim: 1024
        use_linear: true
        use_checkpoint: True
        temporal_conv: True
        temporal_attention: True
        temporal_selfatt_only: true
        temporal_batch_size: -1
        use_causal_attention: false
        temporal_length: 20
        addition_attention: true
        image_cross_attention: true
        traj_cross_attention: true
        default_fs: 30
        fs_condition: true
        resblock_updown: false
        chunk: ${chunk}
        n_view: ${n_view}
        causal_temp_conv: true
        use_block_idx: true
        use_domain_embedding: true
        adapt_to_mvt: True

    first_stage_config:
      target: lvdm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          double_z: True
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: lvdm.modules.encoders.resampler.Resampler
      params:
        dim: 1024
        depth: 4
        dim_head: 64
        heads: 12
        num_queries: 16
        embedding_dim: 14
        output_dim: 1024
        ff_mult: 4

    img_cond_stage_config:
      target: lvdm.modules.encoders.condition.FrozenOpenCLIPImageEmbedderV2
      params:
        abspath: CLIP_WEIGHT_PATH
        freeze: true
    
    image_proj_stage_config:
      target: lvdm.modules.encoders.resampler.Resampler
      params:
        dim: 1024
        depth: 4
        dim_head: 64
        heads: 12
        num_queries: 16
        embedding_dim: 1280
        output_dim: 1024
        ff_mult: 4
        video_length: 16

data:
  target: utils_data.DataModuleFromConfig
  params:
    batch_size: 8
    num_workers: 8 #12
    wrap: false
    train:
      target: lvdm.data.agibotworld_dataset.AgiBotWorld
      params:
        data_roots: ["PATH_TO_AGIBOTWORLD", ]
        domains: ["agibotworld", ]
        sample_size: [320, 512]
        sample_n_frames: 64
        preprocess :  'resize'
        valid_cam :  'head'
        chunk: ${chunk}
        n_previous: ${n_previous}
        previous_pick_mode: 'random'
        action_dim: 7
        random_crop: True
        min_sep: 1
        max_sep: 3

lightning:
  precision: 16
  # strategy: deepspeed_stage_2
  trainer:
    benchmark: True
    accumulate_grad_batches: 1
    max_steps: 100000
    log_every_n_steps: 20
    val_check_interval: 2
    gradient_clip_algorithm: 'norm'
    gradient_clip_val: 0.5
  callbacks:
    model_checkpoint:
      target: pytorch_lightning.callbacks.ModelCheckpoint
      params:
        every_n_train_steps: 30 #1000
        filename: "{epoch}-{step}"
        save_weights_only: True
    metrics_over_trainsteps_checkpoint:
      target: pytorch_lightning.callbacks.ModelCheckpoint
      params:
        filename: '{epoch}-{step}'
        save_weights_only: True
        every_n_train_steps: 20 #20000 # 3s/step*2w=
    batch_logger:
      target: callbacks.ImageLogger
      params:
        batch_frequency:  1
        ### save videos
        to_local: True
        cat_all_to_save: True
        save_dir: runtime_vis_results/expv0
        max_images: 6400
        log_images_kwargs:
          ddim_steps: 27
          unconditional_guidance_scale: 7.5
          timestep_spacing: uniform_trailing
          guidance_rescale: 0.7
          save_fps: 15
